const mealPrepData = [
  // Week 1
  {
    id: "1",
    date: "2023-09-10",
    timeOfDay: "Dinner",
    title: "Grilled Chicken Salad",
    servingSize: "2 servings",
    prepTime: "30 minutes",
    calories: 350,
    rating: 5,
    image: "https://picsum.photos/200",
  },
  {
    id: "2",
    date: "2023-09-11",
    timeOfDay: "Lunch",
    title: "Vegetable Stir-Fry",
    servingSize: "4 servings",
    prepTime: "25 minutes",
    calories: 280,
    rating: 4.5,
    image: "https://picsum.photos/200",
  },

  {
    id: "3",
    date: "2023-09-11",
    timeOfDay: "Dinner",
    title: "Baked Salmon",
    servingSize: "2 servings",
    prepTime: "35 minutes",
    calories: 420,
    rating: 4.8,
    image: "https://picsum.photos/200",
  },
  {
    id: "4",
    date: "2023-09-12",
    timeOfDay: "Breakfast",
    title: "Quinoa Salad",
    servingSize: "3 servings",
    prepTime: "20 minutes",
    calories: 280,
    rating: 4.2,
    image: "https://picsum.photos/200",
  },
  {
    id: "5",
    date: "2023-09-12",
    timeOfDay: "Lunch",
    title: "Greek Salad",
    servingSize: "2 servings",
    prepTime: "15 minutes",
    calories: 220,
    rating: 4.6,
    image: "https://picsum.photos/200",
  },
  {
    id: "6",
    date: "2023-09-13",
    timeOfDay: "Dinner",
    title: "Pasta Primavera",
    servingSize: "4 servings",
    prepTime: "40 minutes",
    calories: 380,
    rating: 4.4,
    image: "https://picsum.photos/200",
  },

  // Week 2
  {
    id: "7",
    date: "2023-09-17",
    timeOfDay: "Lunch",
    title: "Spinach and Feta Omelette",
    servingSize: "2 servings",
    prepTime: "15 minutes",
    calories: 280,
    rating: 4.7,
    image: "https://picsum.photos/200",
  },
  {
    id: "8",
    date: "2023-09-18",
    timeOfDay: "Dinner",
    title: "Teriyaki Salmon",
    servingSize: "2 servings",
    prepTime: "35 minutes",
    calories: 400,
    rating: 4.6,
    image: "https://picsum.photos/200",
  },
  {
    id: "9",
    date: "2023-09-14",
    timeOfDay: "Dinner",
    title: "Teriyaki Salmon",
    servingSize: "2 servings",
    prepTime: "35 minutes",
    calories: 400,
    rating: 4.6,
    image: "https://picsum.photos/200",
  },
  {
    id: "10",
    date: "2023-09-14",
    timeOfDay: "Dinner",
    title: "Teriyaki Salmon",
    servingSize: "2 servings",
    prepTime: "35 minutes",
    calories: 400,
    rating: 4.6,
    image: "https://picsum.photos/200",
  },
  {
    id: "11",
    date: "2023-09-15",
    timeOfDay: "Dinner",
    title: "Teriyaki Salmon",
    servingSize: "2 servings",
    prepTime: "35 minutes",
    calories: 400,
    rating: 4.6,
    image: "https://picsum.photos/200",
  },
  {
    id: "4",
    date: "2023-09-16",
    timeOfDay: "Dinner",
    title: "Baked Salmon",
    servingSize: "2 servings",
    prepTime: "35 minutes",
    calories: 420,
    rating: 4.8,
    image: "https://picsum.photos/200",
  },
  // Add more meal prep items for different weeks and dates
];

export default mealPrepData;
